#!/usr/bin/env python3
"""
BNG Blaster Control Socket Client

Simple script to interact with the BNG Blaster
control socket JSON RPC API.

Christian Giese, January 2021

Copyright (C) 2020-2026, RtBrick, Inc.
SPDX-License-Identifier: BSD-3-Clause
"""
import sys
import socket
import os
import json
import ast

def error(*args, **kwargs):
    """print error and exit"""
    print(*args, file=sys.stderr, **kwargs)
    sys.exit(1)


def usage():
    error("""BNG Blaster CLI Tool

The CLI tool is a simple control socket client
for interactive communication with the BNG Blaster.

{c} <socket> <command> [arguments]

Examples:
    {c} run.sock session-info session-id 1
    {c} run.sock igmp-join session-id 1 group 239.0.0.1 source1 1.1.1.1 source2 2.2.2.2 source3 3.3.3.3
    {c} run.sock igmp-info session-id 1
    {c} run.sock l2tp-csurq tunnel-id 1 sessions [1,2]
""".format(c=sys.argv[0]))
    sys.exit(1)


def build_request(argv):
    request = {}
    request["command"] = argv[2]
    if(len(argv)) > 4:
        request["arguments"] = {}
        for i in range(3, len(argv), 2):
            arg = argv[i+1]
            try:
                # integer arguments like "session-id 1"
                request["arguments"][argv[i]] = int(arg)
            except:
                try:
                    # list arguments like "sessions [1,2]""
                    request["arguments"][argv[i]] = ast.literal_eval(arg)
                except:
                    # string arguments like "group 239.0.0.1"
                    request["arguments"][argv[i]] = arg
    return request


def send_request(socket_path, request):
    if os.path.exists(socket_path):
        client = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        try:
            client.connect(socket_path)
            client.send(json.dumps(request).encode('utf-8'))
            data = ""
            while True:
                junk = client.recv(1024)
                if junk:
                    data += junk.decode('utf-8')
                else:
                    break
            return json.loads(data)
        except Exception as e:
            error(e)
        finally:
            client.close()
    else:
        error("socket %s not found" % socket_path)


def main():
    """main function"""
    if(len(sys.argv)) < 3:
        usage()
    if sys.argv[2] == "help":
        usage()

    socket_path = sys.argv[1]
    try:
        request = build_request(sys.argv)
    except Exception as e:
        error("invalid command")
    #print(json.dumps(request).encode('utf-8'))
    data = send_request(socket_path, request)

    if sys.argv[2] == "commands":
        for cmd in data["commands"]: 
            print("%s %s" % (cmd["command"], str(cmd["arguments"]).replace("', '", "|").replace("'", "")))
    else:
        print(json.dumps(data, indent=4))


if __name__ == "__main__":
    main()
