"""
Shared setup for BNG Blaster ISIS and OSPF against FRR tests

Namespace A runs the BNG Blaster (10.0.0.1, fd00::1), namespace B
runs FRR on the kernel interface (10.0.0.2, fd00::2). The emulated
topology behind the BNG Blaster is generated by lspgen.

Copyright (C) 2020-2026, RtBrick, Inc.
SPDX-License-Identifier: BSD-3-Clause
"""
import json

import helpers
from helpers import BngBlaster, Frr, lspgen, wait_until

BBL_ADDRESS = "10.0.0.1"
BBL_ADDRESS6 = "fd00::1"
BBL_ROUTER_ID = "10.10.0.1"
FRR_ADDRESS = "10.0.0.2"
FRR_ADDRESS6 = "fd00::2"
FRR_ROUTER_ID = "10.10.0.2"

ISIS_AREA = "49.0001"
BBL_SYSTEM_ID = "1921.6800.1001"
FRR_SYSTEM_ID = "1921.6800.1002"
LSPGEN_ROOT_SYSTEM_ID = "1921.6800.0000"
LSPGEN_ROOT_ROUTER_ID = "192.168.0.0"
LSPGEN_ROOT_LINK = "10.10.1.1"
BBL_LINK = "10.10.1.0"

# FRR levels and circuit types by BNG Blaster ISIS level.
FRR_IS_TYPE = {1: "level-1", 2: "level-2-only", 3: "level-1-2"}
FRR_CIRCUIT_TYPE = {1: "level-1", 2: "level-2-only", 3: "level-1-2"}
FRR_ISIS_AUTH = {"md5": "md5", "simple": "clear"}

# Dummy interface prefixes redistributed by FRR.
FRR_PREFIX = "10.99.%d.0/24"
FRR_ADDRESS_DUMMY = "10.99.%d.1/24"
FRR_ADDRESS6_DUMMY = "fd99:%x::1/64"


class LspgenTopology:
    """Topology generated by lspgen, written as MRT file for the BNG
    Blaster and as JSON config to derive the expected nodes and routes."""

    def __init__(self, path, args):
        self.mrt = str(path.with_suffix(".mrt"))
        config = path.with_suffix(".json")
        lspgen(args + ["-m", self.mrt, "-w", str(config)], cwd=str(path.parent))
        self.nodes, self.prefixes, self.prefixes6 = set(), set(), set()
        for nodes in json.loads(config.read_text()).values():
            if not isinstance(nodes, list):
                continue
            for node in nodes:
                self.nodes.add(node["node_id"])
                self.prefixes.update(p["ipv4_prefix"] for p in node.get("ipv4_prefix_list", [])
                                     if p["ipv4_prefix"].endswith("/32"))
                self.prefixes6.update(p["ipv6_prefix"] for p in node.get("ipv6_prefix_list", [])
                                      if p["ipv6_prefix"].endswith("/128"))


def levels(level):
    return [l for l in (1, 2) if level & l]


class IgpSetup:
    """Start FRR in namespace B and the BNG Blaster in namespace A."""

    daemon = None
    logging = ("info",)

    def __init__(self, topology, processes, tmp_path):
        self.topology = topology
        self.processes = processes
        self.tmp_path = tmp_path
        self.frr = None
        self.bbl = None
        helpers.kernel_address(topology.b, topology.if_b,
                               FRR_ADDRESS + "/24", FRR_ADDRESS6 + "/64")

    def start(self, frr=None, bbl=None):
        return self.start_frr(frr).start_bbl(bbl)

    def start_frr(self, frr=None):
        self.frr = Frr(self.topology.b, self.tmp_path, (self.daemon,)).start(
            self.frr_config(**(frr or {})))
        self.processes.append(self.frr)
        return self

    def start_bbl(self, bbl=None):
        self.bbl = BngBlaster(self.topology.a, self.tmp_path).start(
            self.bbl_config(**(bbl or {})), logging=self.logging)
        self.processes.append(self.bbl)
        return self

    def frr_redistribute_connected(self, count):
        """Add prefixes 0 to count-1 on a dummy interface in namespace B
        which FRR redistributes as connected routes."""
        ns = self.topology.b
        ns.exec(["ip", "link", "add", "dummy0", "type", "dummy"])
        ns.exec(["sysctl", "-qw", "net.ipv6.conf.dummy0.disable_ipv6=0"])
        ns.exec(["ip", "link", "set", "dummy0", "up"])
        for i in range(count):
            self.frr_add_prefix(i)

    def frr_add_prefix(self, i):
        self.topology.b.exec(["ip", "addr", "add", FRR_ADDRESS_DUMMY % i, "dev", "dummy0"])
        self.topology.b.exec(["ip", "-6", "addr", "add", FRR_ADDRESS6_DUMMY % i,
                              "dev", "dummy0", "nodad"])

    def frr_del_prefix(self, i):
        self.topology.b.exec(["ip", "addr", "del", FRR_ADDRESS_DUMMY % i, "dev", "dummy0"])
        self.topology.b.exec(["ip", "-6", "addr", "del", FRR_ADDRESS6_DUMMY % i, "dev", "dummy0"])

    def frr_routes(self, afi="ip"):
        """Return prefixes installed by the IGP in the FRR routing table."""
        routes = self.frr.vtysh("show %s route %s" % (afi, self.daemon.rstrip("d")))
        return {prefix for prefix, entries in routes.items()
                if any(e.get("selected") and e.get("installed") for e in entries)}

    def frr_nexthops(self, prefix):
        afi = "ipv6" if ":" in prefix else "ip"
        routes = self.frr.vtysh("show %s route %s" % (afi, prefix))
        return [n.get("ip") for e in routes.get(prefix, []) if e.get("selected")
                for n in e.get("nexthops", [])]

    def teardown(self):
        assert self.bbl.terminate(30) == 0


class IsisSetup(IgpSetup):

    daemon = "isisd"
    logging = ("info", "isis")

    @staticmethod
    def lspgen(path, nodes, level=1, auth=None):
        args = ["-a", "%s/24" % ISIS_AREA, "-c", str(nodes), "-V", str(level),
                "-C", BBL_SYSTEM_ID]
        if auth:
            args += ["-K", auth[1], "-T", auth[0]]
        return LspgenTopology(path, args)

    def frr_config(self, level=1, p2p=True, auth=None, redistribute=False):
        """Return FRR config. The auth tuple (type, key) is used for hellos,
        LSPs and SNPs of all levels."""
        lines = [
            "router isis bbl",
            " net %s.%s.00" % (ISIS_AREA, FRR_SYSTEM_ID),
            " is-type %s" % FRR_IS_TYPE[level],
            " metric-style wide",
            " no hostname dynamic",
            " lsp-gen-interval 1",
            " spf-interval 1",
        ]
        if auth:
            auth = (FRR_ISIS_AUTH[auth[0]], auth[1])
            if level & 1:
                lines.append(" area-password %s %s authenticate snp validate" % auth)
            if level & 2:
                lines.append(" domain-password %s %s authenticate snp validate" % auth)
        if redistribute:
            for l in levels(level):
                lines.append(" redistribute ipv4 connected level-%d" % l)
                lines.append(" redistribute ipv6 connected level-%d" % l)
        lines += [
            "exit",
            "interface %s" % self.topology.if_b,
            " ip router isis bbl",
            " ipv6 router isis bbl",
            " isis circuit-type %s" % FRR_CIRCUIT_TYPE[level],
            " isis hello-interval 1",
            " isis hello-multiplier 10",
        ]
        if p2p:
            lines.append(" isis network point-to-point")
        if auth:
            lines.append(" isis password %s %s" % auth)
        lines.append("exit")
        return "\n".join(lines) + "\n"

    def bbl_config(self, level=1, p2p=True, isis=None, mrt=None):
        instance = {
            "instance-id": 1,
            "level": level,
            "area": ["%s/24" % ISIS_AREA],
            "system-id": BBL_SYSTEM_ID,
            "router-id": BBL_ROUTER_ID,
            "hostname": "BBL",
            "hello-interval": 1,
            "hold-time": 10,
        }
        if mrt:
            connection = {"system-id": "%s.00" % LSPGEN_ROOT_SYSTEM_ID}
            for l in levels(level):
                connection["l%d-metric" % l] = 10
            instance["external"] = {"mrt-file": mrt, "connections": [connection]}
        instance.update(isis or {})
        return {
            "interfaces": {
                "network": {
                    "interface": self.topology.if_a,
                    "address": BBL_ADDRESS + "/24",
                    "gateway": FRR_ADDRESS,
                    "address-ipv6": BBL_ADDRESS6 + "/64",
                    "gateway-ipv6": FRR_ADDRESS6,
                    "isis-instance-id": 1,
                    "isis-level": level,
                    "isis-p2p": p2p
                }
            },
            "isis": [instance]
        }

    def bbl_adjacencies(self):
        return self.bbl.ctrl("isis-adjacencies")["isis-adjacencies"]

    def bbl_adjacency_up(self):
        adjacencies = self.bbl_adjacencies()
        return bool(adjacencies) and all(a["adjacency-state"] == "Up" for a in adjacencies)

    def frr_neighbors(self):
        """Return FRR adjacencies as list of (level, state). The text output
        is parsed, because the JSON output of FRR 10 contains only one level
        of broadcast L1L2 adjacencies."""
        result = []
        for line in self.frr.vtysh("show isis neighbor", json_output=False).splitlines():
            fields = line.split()
            if len(fields) >= 4 and fields[0] == BBL_SYSTEM_ID:
                result.append((int(fields[2]), fields[3]))
        return result

    def frr_adjacency_up(self, level):
        """FRR has an adjacency in state Up for every expected level
        (P2P L1L2 adjacencies are shown as level 3)."""
        up = set()
        for l, state in self.frr_neighbors():
            if state == "Up":
                up.update(levels(l))
        return up == set(levels(level))

    def established(self, level):
        return self.bbl_adjacency_up() and self.frr_adjacency_up(level)

    def wait_established(self, level, timeout=30):
        try:
            wait_until(lambda: self.established(level), timeout, message="ISIS adjacency up")
        except TimeoutError as e:
            raise TimeoutError("%s, BNG Blaster: %s, FRR: %s" % (
                e, self.bbl_adjacencies(), self.frr_neighbors())) from None

    def assert_not_established(self, level, duration=10):
        try:
            wait_until(lambda: self.bbl_adjacency_up() or
                       any(state == "Up" for _, state in self.frr_neighbors()),
                       duration, message="ISIS adjacency")
        except TimeoutError:
            return
        raise AssertionError("ISIS adjacency up unexpectedly")

    def frr_database(self, level):
        """Return {lsp-id: sequence number} of an FRR database level."""
        result = {}
        for area in self.frr.vtysh("show isis database").get("areas", []):
            for db_level in area.get("levels", []):
                if db_level.get("id") != level:
                    continue
                for lsp in db_level.get("lsps", []):
                    result[lsp["lsp"]["id"]] = int(lsp["seqNumber"], 16)
        return result

    def bbl_database(self, level):
        """Return {lsp-id: sequence number} of a BNG Blaster database level."""
        entries = self.bbl.ctrl("isis-database", instance=1, level=level)["isis-database"]
        return {e["id"]: e["seq"] for e in entries}


class OspfSetup(IgpSetup):

    daemon = "ospfd"
    logging = ("info", "ospf")

    @staticmethod
    def lspgen(path, nodes):
        # The protocol must be set before the connector.
        return LspgenTopology(path, ["-P", "ospf2", "-c", str(nodes),
                                     "-C", "%s:%s" % (BBL_ROUTER_ID, LSPGEN_ROOT_LINK)])

    def frr_config(self, p2p=True, auth=None, redistribute=False, priority=None, opaque=True):
        """Return FRR config. The auth tuple is (type, key) with
        type simple or md5 (key ID 1)."""
        lines = [
            "router ospf",
            " ospf router-id %s" % FRR_ROUTER_ID,
            " timers throttle spf 0 50 200",
            " timers throttle lsa all 0",
        ]
        if opaque:
            # Required for the SR opaque LSAs generated by lspgen.
            lines.append(" capability opaque")
        if redistribute:
            lines.append(" redistribute connected")
        lines += [
            "exit",
            "interface %s" % self.topology.if_b,
            " ip ospf network %s" % ("point-to-point" if p2p else "broadcast"),
            " ip ospf hello-interval 1",
            " ip ospf dead-interval 4",
        ]
        if priority is not None:
            lines.append(" ip ospf priority %d" % priority)
        if auth and auth[0] == "md5":
            lines += [" ip ospf authentication message-digest",
                      " ip ospf message-digest-key 1 md5 %s" % auth[1]]
        elif auth:
            lines += [" ip ospf authentication",
                      " ip ospf authentication-key %s" % auth[1]]
        # The area enables OSPF on the interface, so it must be configured
        # last, otherwise the wait timer starts with the default dead interval.
        lines += [" ip ospf area 0.0.0.0", "exit"]
        return "\n".join(lines) + "\n"

    def bbl_config(self, p2p=True, ospf=None, mrt=None):
        instance = {
            "instance-id": 1,
            "version": 2,
            "router-id": BBL_ROUTER_ID,
            "hostname": "BBL",
            "hello-interval": 1,
            "dead-interval": 4,
        }
        if mrt:
            instance["external"] = {"mrt-file": mrt, "connections": [{
                "router-id": LSPGEN_ROOT_ROUTER_ID,
                "local-ipv4-address": BBL_LINK,
                "metric": 10
            }]}
        instance.update(ospf or {})
        return {
            "interfaces": {
                "network": {
                    "interface": self.topology.if_a,
                    "address": BBL_ADDRESS + "/24",
                    "gateway": FRR_ADDRESS,
                    "ospfv2-instance-id": 1,
                    "ospfv2-type": "p2p" if p2p else "broadcast"
                }
            },
            "ospf": [instance]
        }

    def bbl_neighbors(self):
        return self.bbl.ctrl("ospf-neighbors", instance=1)["ospf-neighbors"]

    def bbl_interface(self):
        return self.bbl.ctrl("ospf-interfaces", instance=1)["ospf-interfaces"][0]

    def bbl_full(self):
        neighbors = self.bbl_neighbors()
        return len(neighbors) == 1 and neighbors[0]["state"] == "Full"

    def frr_interface_state(self):
        """Return FRR interface state (e.g. DR)."""
        interfaces = self.frr.vtysh("show ip ospf interface").get("interfaces", {})
        return interfaces.get(self.topology.if_b, {}).get("state")

    def frr_neighbor_state(self):
        """Return FRR neighbor state (e.g. Full/DR) of the BNG Blaster."""
        neighbors = self.frr.vtysh("show ip ospf neighbor").get("neighbors", {})
        for entry in neighbors.get(BBL_ROUTER_ID, []):
            return entry.get("nbrState")
        return None

    def frr_full(self):
        return (self.frr_neighbor_state() or "").startswith("Full")

    def established(self):
        return self.bbl_full() and self.frr_full()

    def wait_established(self, timeout=30):
        try:
            wait_until(self.established, timeout, message="OSPF neighbor full")
        except TimeoutError as e:
            raise TimeoutError("%s, BNG Blaster: %s, FRR: %s" % (
                e, self.bbl_neighbors(), self.frr_neighbor_state())) from None

    def assert_not_established(self, duration=10):
        try:
            wait_until(lambda: self.bbl_full() or self.frr_full(), duration,
                       message="OSPF neighbor")
        except TimeoutError:
            return
        raise AssertionError("OSPF neighbor full unexpectedly")

    def bbl_database(self):
        return self.bbl.ctrl("ospf-database", instance=1)["ospf-database"]

    def frr_router_lsas(self):
        """Return advertising router IDs of all router LSAs in area 0."""
        database = self.frr.vtysh("show ip ospf database router")
        areas = database.get("routerLinkStates", {}).get("areas", {})
        return {lsa.get("advertisingRouter") for lsa in areas.get("0.0.0.0", [])}
