"""
BNG Blaster BGP EVPN against GoBGP

GoBGP originates all EVPN route types (MPLS and VXLAN) which are
learned by the BNG Blaster, and the BNG Blaster sends EVPN VPWS
Ethernet A-D routes generated by bgpupdate to GoBGP.

Copyright (C) 2020-2026, RtBrick, Inc.
SPDX-License-Identifier: BSD-3-Clause
"""
import pytest

from bgp_common import BBL_ADDRESS, BBL_AS, GOBGP_ADDRESS, BgpSetup
from helpers import bgpupdate, gobgp_mpls_label, wait_until

RD = "65001:100"
RT = "65001:100"
ESI = ["esi", "AS", "65001", "100"]
ESI_STR = "05:00:00:fd:e9:00:00:00:64:00"
MAC = "02:00:00:00:00:01"

pytestmark = pytest.mark.usefixtures("gobgp_bin")


@pytest.fixture
def bgp(topology, processes, tmp_path):
    return BgpSetup(topology, processes, tmp_path)


def evpn(bgp, action, route):
    bgp.gobgp.cli(["global", "rib", "-a", "evpn", action] + route, json_output=False)


def mpls(label):
    return str(gobgp_mpls_label(label))


def prefix_route(label):
    return ["prefix", "192.168.10.0/24", "gw", "0.0.0.0", "etag", "0", "label", mpls(label),
            "rd", RD, "rt", RT, "encap", "mpls"]


ROUTES = {
    1: ["a-d"] + ESI + ["etag", "100", "label", mpls(1001), "rd", RD, "rt", RT, "encap", "mpls"],
    2: ["macadv", MAC, "10.1.1.10", "etag", "0", "label", "%s,%s" % (mpls(2001), mpls(2002)),
        "rd", RD, "rt", RT, "encap", "mpls"],
    3: ["multicast", GOBGP_ADDRESS, "etag", "0", "rd", RD, "rt", RT, "encap", "mpls"],
    4: ["esi", GOBGP_ADDRESS] + ESI + ["rd", RD, "rt", RT, "encap", "mpls"],
    5: prefix_route(5001),
}


def routes_by_type(bgp):
    return {r["route-type"]: r for r in bgp.bbl_evpn_routes() if r["active"]}


def test_evpn_route_types(bgp):
    bgp.start(families=("evpn",))
    bgp.wait_established()
    for route in ROUTES.values():
        evpn(bgp, "add", route)
    routes = wait_until(lambda: len(routes_by_type(bgp)) == 5 and routes_by_type(bgp), 15,
                        message="all EVPN route types learned")
    for route in routes.values():
        assert route["rd"] == RD
        assert route["nexthop"] == GOBGP_ADDRESS
        assert RT in route["route-targets"]
        assert route["encapsulation"] == "mpls"

    assert routes[1]["esi"] == ESI_STR
    assert routes[1]["ethernet-tag"] == 100
    assert routes[1]["label1"] == 1001
    assert routes[2]["mac"] == MAC
    assert routes[2]["ip"] == "10.1.1.10"
    assert routes[2]["label1"] == 2001
    assert routes[2]["label2"] == 2002
    assert routes[4]["esi"] == ESI_STR
    assert routes[5]["prefix"] == "192.168.10.0/24"
    assert routes[5]["label1"] == 5001

    evpn(bgp, "del", ROUTES[2])
    wait_until(lambda: not any(r["active"] for r in bgp.bbl_evpn_routes(**{"route-type": 2})),
               10, message="EVPN MAC/IP route withdrawn (inactive)")
    assert len(routes_by_type(bgp)) == 4
    bgp.teardown()


def test_evpn_vxlan(bgp):
    """Labels of VXLAN routes are 24 bit VNIs (RFC 8365)."""
    bgp.start(families=("evpn",))
    bgp.wait_established()
    evpn(bgp, "add", ["macadv", MAC, "10.1.1.10", "etag", "0", "label", "10100",
                      "rd", RD, "rt", RT, "encap", "vxlan"])
    route = wait_until(lambda: routes_by_type(bgp).get(2), 15, message="EVPN VXLAN route")
    assert route["encapsulation"] == "vxlan"
    assert route["label1"] == 10100
    bgp.teardown()


def test_evpn_stream_label(bgp):
    """Stream resolves the inner label from the learned IP prefix route."""
    streams = [{
        "name": "EVPN-T5",
        "type": "ipv4",
        "direction": "downstream",
        "pps": 10,
        "network-interface": bgp.topology.if_a,
        "destination-ipv4-address": "192.168.10.1",
        "bgp-evpn-rd": RD,
        "bgp-evpn-prefix": "192.168.10.0/24"
    }]
    bgp.start(families=("evpn",), bbl={"streams": streams})
    bgp.wait_established()
    evpn(bgp, "add", ROUTES[5])
    wait_until(lambda: routes_by_type(bgp).get(5), 15, message="EVPN IP prefix route")
    bgp.bbl.ctrl("traffic-start")

    def resolved():
        info = bgp.bbl.ctrl("stream-info", **{"flow-id": 1})["stream-info"]
        return info.get("evpn-resolved") and info

    info = wait_until(resolved, 10, message="EVPN stream label resolved")
    assert info["evpn-label"] == 5001

    # Label change must be applied to the stream.
    evpn(bgp, "add", prefix_route(5002))
    wait_until(lambda: resolved() and resolved()["evpn-label"] == 5002, 10,
               message="EVPN stream label updated")
    bgp.bbl.ctrl("traffic-stop")
    bgp.teardown()


def test_evpn_vpws_to_gobgp(bgp, tmp_path):
    """EVPN VPWS Ethernet A-D per EVI routes sent by the BNG Blaster."""
    services = 4
    path = str(tmp_path / "evpn.bgp")
    bgpupdate(["-f", path, "-a", str(BBL_AS), "-n", BBL_ADDRESS, "--evpn-vpws",
               "--rd", "65000:1", "--rt", "65000:1", "-m", "1000",
               "--service-id", "100", "--service-num", str(services), "--end-of-rib"])
    bgp.start(families=("evpn",), bbl={"bgp": {"raw-update-file": path}})
    bgp.wait_established()
    wait_until(lambda: len(bgp.gobgp.adj_in(BBL_ADDRESS, "evpn")) == services, 15,
               message="GoBGP EVPN A-D routes received")
    bgp.teardown()
